name: PHPUnit

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  setup:

    strategy:
      fail-fast: false
      matrix:
        php-versions: 
          - 7.3
          - 7.4
        composer-stability:
          # - '--prefer-lowest --prefer-stable'
          - '--prefer-stable'
          # - ''
        database:
          - MYSQL
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up PHP
      uses: maxime-rainville/silverstripe-ci-setup@master
      with:
        composer-stability: ${{ matrix.composer-stability }}
        phpVersion: ${{ matrix.php-versions }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Echo PHP
      run: php -v
    - name: Run test suite
      uses: maxime-rainville/silverstripe-ci-phpunit@master
      with:
        composer-stability: ${{ matrix.composer-stability }}
        phpVersion: ${{ matrix.php-versions }}
