name: PHPUnit

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        php-versions: 
          - 7.3
          - 7.4
        composer-stability:
          - '--prefer-lowest --prefer-stable'
          - '--prefer-stable'
          - ''
        database:
          - MYSQL
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Run test suite
      uses: maxime-rainville/silverstripe-ci-phpunit@master
      with:
        composer-stability: ${{ matrix.composer-stability }}
